parameters:
#    acme_task.example.class: Acme\TaskBundle\Example

services:
    acme_demo.form.type.task:
        class: Acme\TaskBundle\Form\Type\TaskType
        tags:
          - { name: form.type, alias: task }

